# Generated by Django 3.0.6 on 2020-05-13 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('emp_Id', models.CharField(max_length=4)),
                ('initial_Id', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=50)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves', models.CharField(choices=[('Vacation', 'Vacation Leave'), ('Personal', 'Personal Leave'), ('Sick', 'Sick Leave')], default='Vactaion', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('Fullday', 'Full Day'), ('Halfday', 'Half Day')], default='Fullday', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveDate', models.DateField()),
                ('leaveEndDate', models.DateField()),
                ('createTime', models.DateField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_online_system.LeaveType')),
                ('fullName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_online_system.Employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_online_system.Position')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_online_system.Type')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_online_system.LeaveType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_online_system.Position'),
        ),
    ]
