# Generated by Django 3.0.6 on 2020-05-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_online_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='choices',
            field=models.CharField(choices=[('Full day', 'Full Day'), ('Half day', 'Half Day')], default='Fullday', max_length=30),
        ),
    ]
