# Generated by Django 3.0.6 on 2020-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_online_system', '0002_auto_20200513_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='leaves',
            field=models.CharField(choices=[('Vacation', 'Vacation Leave'), ('Personal', 'Personal Leave'), ('Sick', 'Sick Leave'), ('Ordination leave', 'Ordination leave'), ('Marriage leave', 'Marriage leave'), ('Military service leave', 'Military service leave'), ('Study leave', 'Study leave'), ('Maternity leave', 'Maternity leave'), ('Compassionate/Bereavement leave', 'compassionate/bereavement leave'), ('Accident', 'Accident')], default='Vactaion', max_length=300),
        ),
    ]
